[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Ativa a partição de 3MB para aplicativos grandes (muda de 95% para ~30%)
board_build.partitions = huge_app.csv

monitor_speed = 115200

; otimização (opcional)
build_flags = 
    -DCORE_DEBUG_LEVEL=0

; bibliotecas
lib_deps =
    bodmer/TFT_eSPI